### ISSUE TITLE
Score should be more dependent on time.

### ISSUE THREAD

**Issue by dtinth** [ReiiYuki/100-thai-flag-game#62]
Right now the score bonus is 100/t. The problem is that those who clear the game will have roughly the same score.

| Time taken | Score |
| ----:| ----:|
| 33–50s | 1902 |
| 50–100s | 1901 |
| 100s | 1900 |

![screenshot_20170218-211605](https://cloud.githubusercontent.com/assets/193136/23100083/b7f0e872-f6a9-11e6-9b87-63ed2a1647d3.png)

## Proposed alternative scoring formula

My proposed scoring formula: 100<var>h</var> [height score] + 1000<var>e</var><sup>-<var>t</var>/100</sup> [time score]

Time score rate is determined by ∂/∂<var>t</var>(100<var>h</var> + 1000<var>e</var><sup>-<var>t</var>/100</sup>) = -10<var>e</var><sup>-<var>t</var>/100</sup>

| Time (<var>t</var>) | Time score | Rate (pts/sec) |
| ----:| ----:| ----:|
| 0 | 1000 | -10.0 |
| 20 | 818 | -8.2 |
| 40 | 670 | -6.7 |
| 60 | 548 | -5.5 |
| 80 | 449 | -4.5 |
| 100 | 367 | -3.7 |
| 120 | 301 | -3.0 |
| 140 | 246 | -2.5 |
| 160 | 201 | -2.0 |
| 180 | 165 | -1.7 |

Therefore the maximum score is 20,000 points.

**Comment by ReiiYuki** [comment]
Thank you for good suggestion.

In fact, we are thinking the way to make more relationship between time and score. So new score calculation will update soon.

**Comment by ReiiYuki** [comment]
Now I use your suggested scoring system and it will be on 1.2.0 version update. Thank! :D

#64
